[server]
headless = true
address = "0.0.0.0"
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#bf3a14"
backgroundColor = "#f6f2eb"
secondaryBackgroundColor = "#f0ebe0"
textColor = "#1c1814"
font = "sans serif"