[server]
headless = true
address = "0.0.0.0"
fileWatcherType = "none"
enableStaticServing = false

[runner]
fastReruns = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#c03b15"
backgroundColor = "#f6f2eb"
secondaryBackgroundColor = "#f0ebe0"
textColor = "#1c1814"
font = "sans serif"