"""create document tables

Revision ID: 1ccffca356d9
Revises: 20260518_0001
Create Date: 2026-05-18 18:41:09.268401+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '1ccffca356d9'
down_revision = '20260518_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
