"""fix drive sync repository compatibility

Revision ID: 91f4f29d0f4a
Revises: 1ccffca356d9
Create Date: 2026-05-20 11:33:56.394590+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '91f4f29d0f4a'
down_revision = '1ccffca356d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source', sa.String(length=64), nullable=True))
    op.add_column('sync_runs', sa.Column('updated_files', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_runs', 'updated_files')
    op.drop_column('documents', 'source')
    # ### end Alembic commands ###
